version: '3'
services:
    app:
        build:
            context: .
            args:
                HOST_DEV_USER: $HOST_DEV_USER
                HOST_DEV_UID: $HOST_DEV_UID
                HOST_DEV_GID: $HOST_DEV_GID
        tty: true
        ports:
            - "80:8080"
            # - "443:443"
            # Debugger port.
            - "9229:9229"
        volumes:
            - ./app:/app
        depends_on:
            - solr
    solr:
        image: solr:8.9
        ports:
            - "8983:8983"
        volumes:
            - solr-data:/var/solr
        command:
            - solr-precreate
            - gettingstarted

volumes:
    solr-data:
